# sudo docker-compose build
# sudo docker-compose up
# sudo docker-compose up --build

# Subir em background
# sudo docker-compose -f docker-compose.yml up -d

# How use iterative mode container
# sudo docker-compose exec apache_php bash


#Purging All Unused or Dangling Images, Containers, Volumes, and Networks
#sudo docker system prune -a

version: '3.8'
services:

  cnpjrfb:
    build:      
      context: .
      dockerfile: Dockerfile
    image: cnpjrfb:v2
    container_name: cnpjrfb
    restart: always    
    ports:
      - "80:80"
    networks:
      - cnpj-network
    volumes:
      - ./www:/var/www/html:rw            #WWW ROOT
      - ./log_apache:/var/log/apache2:rw  #Log Apahce
      - ./log_postgresql:/var/log/postgresql:rw  #Log PosgreSQL
      - ./postgresql:/var/lib/postgresql/data:rw
      - ./dados_receita:/var/opt/dados_receita:rw

networks: 
    cnpj-network:
        driver: bridge